name: Publish

"on":
  push:
    branches: [master]

jobs:
  validate-release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[publish]')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.12.196

      - name: Validate plugins
        run: bb validate

      - name: Run script tests
        run: bb test
